<a href="https://colab.research.google.com/github/HazardKrish/HazardKrish/blob/main/Experiment_2(a).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#experiment 2.a
import numpy as np


In [ ]:
#Defining n dimensional zero array
#np.zeroes=> give a np array filled with zeros
c=np.zeros([4,3,2])
print(c)
print(c.ndim)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
3


In [ ]:
#Defining one dimensionally equally spaced non zero array
c=np.linspace(4,30,10)
print(c)


[ 4.          4.53061224  5.06122449  5.59183673  6.12244898  6.65306122
  7.18367347  7.71428571  8.24489796  8.7755102   9.30612245  9.83673469
 10.36734694 10.89795918 11.42857143 11.95918367 12.48979592 13.02040816
 13.55102041 14.08163265 14.6122449  15.14285714 15.67346939 16.20408163
 16.73469388 17.26530612 17.79591837 18.32653061 18.85714286 19.3877551
 19.91836735 20.44897959 20.97959184 21.51020408 22.04081633 22.57142857
 23.10204082 23.63265306 24.16326531 24.69387755 25.2244898  25.75510204
 26.28571429 26.81632653 27.34693878 27.87755102 28.40816327 28.93877551
 29.46938776 30.        ]


In [ ]:
#Difference between list and array
c=list(range(16))
print(c)
d=np.array(c)
print(d)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [ ]:
e=np.array(list(range(16)))
print(e)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [ ]:
#Creating n integers
c=np.arange(24).reshape(2,1,12)
print(c,type(c))

[[[ 0  1  2  3  4  5  6  7  8  9 10 11]]

 [[12 13 14 15 16 17 18 19 20 21 22 23]]] <class 'numpy.ndarray'>


In [ ]:
h=np.linspace(3,9)
print(h)

[3.         3.12244898 3.24489796 3.36734694 3.48979592 3.6122449
 3.73469388 3.85714286 3.97959184 4.10204082 4.2244898  4.34693878
 4.46938776 4.59183673 4.71428571 4.83673469 4.95918367 5.08163265
 5.20408163 5.32653061 5.44897959 5.57142857 5.69387755 5.81632653
 5.93877551 6.06122449 6.18367347 6.30612245 6.42857143 6.55102041
 6.67346939 6.79591837 6.91836735 7.04081633 7.16326531 7.28571429
 7.40816327 7.53061224 7.65306122 7.7755102  7.89795918 8.02040816
 8.14285714 8.26530612 8.3877551  8.51020408 8.63265306 8.75510204
 8.87755102 9.        ]


In [ ]:
x=list(range(3,9))
y=np.array(x).reshape(3,2)
print(y)


[[3 4]
 [5 6]
 [7 8]]


In [ ]:
#Logical and Relational operations with n dimensional array
print(y)
print(y<=6)

[[3 4]
 [5 6]
 [7 8]]
[[ True  True]
 [ True  True]
 [False False]]


In [ ]:
#Scientific operations on single element in an array
print(np.sin(y),end="\n")
print(np.cos(y),end="\n")
print(np.sqrt(y),end="\n")
print(np.log(y),end="\n")
print(np.exp(y),end="\n")

[[ 0.14112001 -0.7568025 ]
 [-0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825]]
[[-0.9899925  -0.65364362]
 [ 0.28366219  0.96017029]
 [ 0.75390225 -0.14550003]]
[[1.73205081 2.        ]
 [2.23606798 2.44948974]
 [2.64575131 2.82842712]]
[[1.09861229 1.38629436]
 [1.60943791 1.79175947]
 [1.94591015 2.07944154]]
[[  20.08553692   54.59815003]
 [ 148.4131591   403.42879349]
 [1096.63315843 2980.95798704]]
